---
- name: Generate a new keypair at localhost
  hosts: localhost
  become: yes
  tasks:
  
    - name: Create new keypair
      openssh_keypair:
        owner: ubuntu
        group: admin
        path: /home/ubuntu/.ssh/id_rsa

- name: Create user on nodes and copy the keypair to authorized_key file
  hosts: nodes
  become: yes
  vars:
    user_name: roeef  
  tasks:

    - name: Create a new user on nodes
      user:
        name: "{{ user_name }}"
        group: admin
        shell: /bin/bash

    - name: copy the keypair to authorized_key file
      authorized_key:
        user: "{{ user_name }}"
        key: "{{ lookup('file', '/home/ubuntu/.ssh/id_rsa.pub') }}"
        state: present