---
- name: Create new user and generate a Keypair
  hosts: localhost
  remote_user: ubuntu
  become: yes
  vars:
    user_name: mark
    user_password: 111111
  tasks:

    - name: Create a new user with ssh key
      user:
       name: "{{ user_name }}"
       password: "{{ '{{ user_password }}' | password_hash('sha512', '{{ user_name }}') }}"
       generate_ssh_key: yes



- name: Create user on nodes
  hosts:  nodes
  remote_user: ubuntu
  become: yes
  vars:
    user_name: mark
    user_password: 111111
    
  tasks:
    - name: Create a new user on nodes with ssh key
      user:
       name: "{{ user_name }}"
       password: "{{ '{{ user_password }}' | password_hash('sha512', '{{ user_name }}') }}"

    - name: 
      authorized_key:
        user: "{{ user_name }}"
        key: "{{ lookup('file', '/home/{{ user_name }}/.ssh/id_rsa.pub') }}"
        state: present